# queries and commands that can be performed against each device

# TODO:
# - nvmlDeviceClearCpuAffinity
# - nvmlDeviceGetAPIRestriction
# - nvmlDeviceGetApplicationsClock
# - nvmlDeviceGetAutoBoostedClocksEnabled
# - nvmlDeviceGetBAR1MemoryInfo
# - nvmlDeviceGetBoardId
# - nvmlDeviceGetBrand
# - nvmlDeviceGetBridgeChipInfo
# - nvmlDeviceGetClockInfo
# - nvmlDeviceGetComputeMode
# - nvmlDeviceGetComputeRunningProcesses
# - nvmlDeviceGetCount
# - nvmlDeviceGetCpuAffinity
# - nvmlDeviceGetCurrentClocksThrottleReasons
# - nvmlDeviceGetCurrPcieLinkGeneration
# - nvmlDeviceGetCurrPcieLinkWidth
# - nvmlDeviceGetDecoderUtilization
# - nvmlDeviceGetDefaultApplicationsClock
# - nvmlDeviceGetDetailedEccErrors
# - nvmlDeviceGetDisplayActive
# - nvmlDeviceGetDisplayMode
# - nvmlDeviceGetDriverModel
# - nvmlDeviceGetEccMode
# - nvmlDeviceGetEncoderUtilization
# - nvmlDeviceGetEnforcedPowerLimit
# - nvmlDeviceGetFanSpeed
# - nvmlDeviceGetGpuOperationMode
# - nvmlDeviceGetGraphicsRunningProcesses
# - nvmlDeviceGetHandleByIndex
# - nvmlDeviceGetHandleByPciBusId
# - nvmlDeviceGetHandleBySerial
# - nvmlDeviceGetHandleByUUID
# - nvmlDeviceGetIndex
# - nvmlDeviceGetInforomConfigurationChecksum
# - nvmlDeviceGetInforomImageVersion
# - nvmlDeviceGetInforomVersion
# - nvmlDeviceGetMaxClockInfo
# - nvmlDeviceGetMaxPcieLinkGeneration
# - nvmlDeviceGetMaxPcieLinkWidth
# - nvmlDeviceGetMemoryErrorCounter
# - nvmlDeviceGetMemoryInfo
# - nvmlDeviceGetMinorNumber
# - nvmlDeviceGetMultiGpuBoard
# - nvmlDeviceGetName
# - nvmlDeviceGetPcieReplayCounter
# - nvmlDeviceGetPcieThroughput
# - nvmlDeviceGetPciInfo
# - nvmlDeviceGetPerformanceState
# - nvmlDeviceGetPersistenceMode
# - nvmlDeviceGetPowerManagementDefaultLimit
# - nvmlDeviceGetPowerManagementLimit
# - nvmlDeviceGetPowerManagementLimitConstraints
# - nvmlDeviceGetPowerManagementMode
# - nvmlDeviceGetPowerState
# - nvmlDeviceGetPowerUsage
# - nvmlDeviceGetRetiredPages
# - nvmlDeviceGetRetiredPagesPendingStatus
# - nvmlDeviceGetSamples
# - nvmlDeviceGetSerial
# - nvmlDeviceGetSupportedClocksThrottleReasons
# - nvmlDeviceGetSupportedGraphicsClocks
# - nvmlDeviceGetSupportedMemoryClocks
# - nvmlDeviceGetTemperature
# - nvmlDeviceGetTemperatureThreshold
# - nvmlDeviceGetTopologyCommonAncestor
# - nvmlDeviceGetTopologyNearestGpus
# - nvmlDeviceGetTotalEccErrors
# - nvmlDeviceGetUtilizationRates
# - nvmlDeviceGetUUID
# - nvmlDeviceGetVbiosVersion
# - nvmlDeviceGetViolationStatus
# - nvmlDeviceOnSameBoard
# - nvmlDeviceResetApplicationsClocks
# - nvmlDeviceSetAutoBoostedClocksEnabled
# - nvmlDeviceSetCpuAffinity
# - nvmlDeviceSetDefaultAutoBoostedClocksEnabled
# - nvmlDeviceValidateInforom
# - nvmlSystemGetTopologyGpuSet
# - nvmlDeviceClearEccErrorCounts
# - nvmlDeviceSetAPIRestriction
# - nvmlDeviceSetApplicationsClocks
# - nvmlDeviceSetComputeMode
# - nvmlDeviceSetDriverModel
# - nvmlDeviceSetEccMode
# - nvmlDeviceSetGpuOperationMode
# - nvmlDeviceSetPersistenceMode
# - nvmlDeviceSetPowerManagementLimit